version: '3.7'

services:
  api_observasampa:
    build:
      context: ./api_observasampa
    container_name: api_observasampa
    image: api_observasampa
    environment:
      ENV: ${ENV}
    env_file: .env
    restart: unless-stopped
    networks:
      - api_observa_network

  web:
    container_name: nginx
    build: nginx
    ports:
        - 80:80
        - 443:443
    volumes:
        - ${NGINX_LOGS_VOLUME}:/var/log/nginx/
        - ${NGINX_CACHE_VOLUME}:/data/nginx/cache
    depends_on:
        - api_observasampa
    networks:
        - api_observa_network


networks:
  api_observa_network:
    driver: bridge
    name: api_observa_network
